import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// ビルド成果物のコピー先（Vault 内のプラグインフォルダ）。
// 既定は dev-vault。別の Vault で試すときは OBSIDIAN_PLUGIN_DIR で上書きする。
//   OBSIDIAN_PLUGIN_DIR="/path/to/Vault/.obsidian/plugins/pdf-simple" npm run dev
const manifest = JSON.parse(readFileSync('manifest.json', 'utf8'));
const pluginDir =
	process.env.OBSIDIAN_PLUGIN_DIR ??
	path.join('dev-vault', '.obsidian', 'plugins', manifest.id);

/** @type {import('esbuild').Plugin} */
const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			const pluginsRoot = path.dirname(pluginDir);
			if (!existsSync(pluginsRoot)) {
				console.log(
					`[copy-to-vault] skip: ${pluginsRoot} が無い（npm run vault:setup で作成）`,
				);
				return;
			}
			mkdirSync(pluginDir, { recursive: true });
			for (const file of ['main.js', 'manifest.json', 'styles.css']) {
				if (existsSync(file))
					copyFileSync(file, path.join(pluginDir, file));
			}
			// hot-reload プラグインはこのファイル（または .git）がある plugin フォルダだけを監視する
			const marker = path.join(pluginDir, '.hotreload');
			if (!existsSync(marker)) writeFileSync(marker, '');
			console.log(`[copy-to-vault] -> ${pluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [copyToVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
